### ISSUE TITLE
你好，我们能交流一下吗

### ISSUE THREAD

**Issue by Renormalizedpotato** [Xiao-dong-Wang/Multifidelity-GP#1]

**Comment by Xiao-dong-Wang** [comment]
好的呀

**Comment by Renormalizedpotato** [comment]
我注意到你是复现了rassi他们nargp的论文。一个维度表现的很好。更高维度的情形请问你有没有测试过，比如十维以上？貌似维度高的时候比较难以提现优势

**Comment by Xiao-dong-Wang** [comment]
嗯，NARGP相对GP拟合效果的提升却决于低置信度源和高置信度目标的相似性，维度越高差异可能会更大。我没有做过很高维度的例子，做过一个6维问题的研究（An Efficient and Robust Yield Optimization Method for High-dimensional SRAM Circuits），基于MFGP的贝叶斯优化方法，在这个问题上，低置信度数据对高置信度拟合是有益的。据我所知，文章《An
efficient multi-fidelity bayesian optimization approach for analog circuit synthesis》中做了一个36维的问题，从结果来看，应该也是有效的。

**Comment by Xiao-dong-Wang** [comment]
> 我注意到你是复现了rassi他们nargp的论文。一个维度表现的很好。更高维度的情形请问你有没有测试过，比如十维以上？貌似维度高的时候比较难以提现优势

**Comment by Xiao-dong-Wang** [comment]
> > 我注意到你是复现了rassi他们nargp的论文。一个维度表现的很好。更高维度的情形请问你有没有测试过，比如十维以上？貌似维度高的时候比较难以提现优势

嗯，NARGP相对GP拟合效果的提升却决于低置信度源和高置信度目标的相似性，维度越高差异可能会更大。我没有做过很高维度的例子，做过一个6维问题的研究（An Efficient and Robust Yield Optimization Method for High-dimensional SRAM Circuits），基于MFGP的贝叶斯优化方法，在这个问题上，低置信度数据对高置信度拟合是有益的。据我所知，文章《An
efficient multi-fidelity bayesian optimization approach for analog circuit synthesis》中做了一个36维的问题，从结果来看，应该也是有效的。

**Comment by Renormalizedpotato** [comment]
还有，如果这个出现了nopositive definite, even with jitter的问题，一般如何处理？毕竟是数据融合的结构，如果在矩阵对角线加噪声会不会影响数据融合模型的输出？

**Comment by Xiao-dong-Wang** [comment]
> 还有，如果这个出现了nopositive definite, even with jitter的问题，一般如何处理？毕竟是数据融合的结构，如果在矩阵对角线加噪声会不会影响数据融合模型的输出？

这个问题在GP的训练中是常见的，常用的解决办法就是在对角线上加微小的扰动，你可以先加一个极微小的扰动，如1e-20，如果仍然报错，再加1e-19，迭代下去。这种操作不会对模型输出产生较大影响，因为只是在对角线上增加扰动，相当于增加了噪声水平，GP是可以处理数据噪声的，不影响数据点之间“相似性”的计算（非对角元）
