### ISSUE TITLE
请教NARGP问题

### ISSUE THREAD

**Issue by coderxulh** [Xiao-dong-Wang/Multifidelity-GP#2]
你好，不知道可否请教一下关于你的MF-GP复现代码的问题？
我最近尝试了一下你的代码，发现在test1和test2中都出现了相邻两次运行结果不同的问题，这应该是属于随机种子不同导致的。当我尝试固定随机种子时，发现在某些随机种子下预测效果表现得不错，而其它随机种子则表现比较糟糕。（有时候甚至出现预测均值为一条直线(flat)的情况）
想请问一下你，这种问题是什么原因造成的？是算法的不稳定吗？进一步的，要如何才能避免出现flat这种情况呢？
谢谢！

**Comment by Xiao-dong-Wang** [comment]
这应该是GP训练过程中矩阵运算的问题，在GP训练过程中受到超参数影响可能会出现矩阵非半正定等问题，而超参数又随着训练迭代不断变化（这里使用的是BFGS，一种梯度优化算法），所以某些种子可能产生不好的超参数，对应很差的拟合效果。可以利用多起始点方法（随机设置多组超参数作为训练初始解），设计更好的超参数，利用多组种子，修改优化获取函数方法等方法避免这种情况。
